### ISSUE TITLE
Level Tracking and Win Condition

### ISSUE THREAD

**Issue by REMarriott** [balaam/tiny_rogue#59]
- [x] Have a system that can tell what level of the dungeon the player is on (Let's start a 1 instead of 0 :))
- [x] Add a decision about when a given level will be the last level. Hard coded - level 3 for instance would be fine. 
- [x] Add winning item to final level (currently a crown)
- [x] The end tile should be reachable from the players starting position 
- [x] The player should always be able to walk from their starting position to the down staircase (otherwise they're trapped and the game is unwinnable!)

Note: Unless you want to don't bother with up-staircases. It makes things simpler if we don't have to worry about the state of previous levels
